spring:
  config:
    import: optional:configserver:http://config-service:8888
  application:
    name: gateway-service
  profiles:
    active: dev
  server:
    port: 8080
  output:
    ansi:
      enabled: always
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user-service/**
          filters:
            - StripPrefix=1
            - AuthFilterFactory
        - id: professional-service
          uri: lb://professional-service
          predicates:
            - Path=/professional-service/**
          filters:
            - StripPrefix=1
            - AuthFilterFactory
        - id: schedule-service
          uri: lb://schedule-service
          predicates:
            - Path=/schedule-service/**
          filters:
            - StripPrefix=1
            - AuthFilterFactory
        - id: nutrition-service
          uri: lb://nutrition-service
          predicates:
            - Path=/nutrition-service/**
          filters:
            - StripPrefix=1
            - AuthFilterFactory
        - id: psychological-service
          uri: lb://psychological-service
          predicates:
            - Path=/psychological-service/**
          filters:
            - StripPrefix=1
            - AuthFilterFactory
        - id: physical-activity-service
          uri: lb://physical-activity-service
          predicates:
            - Path=/physical-activity-service/**
          filters:
            - StripPrefix=1
            - AuthFilterFactory
        - id: authentication-service
          uri: lb://authentication-service
          predicates:
            - Path=/authentication-service/**
          filters:
            - StripPrefix=1
        - id: config-server
          uri: http://config-service:8888/
          predicates:
            - Path=/config-service/**
          filters:
            - StripPrefix=1
        - id: openapi
          uri: http://localhost:8080
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/?(?<segment>.*), /$\{segment}/v3/api-docs

#- RewritePath=/user-service/?(?<segment>.*),/$\{segment\}

# Actuator
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include: "*"

# Discovery Server
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true


springdoc:
  swagger-ui:
    urls:
      - name: user-service
        url: /v3/api-docs/user-service
      - name: professional-service
        url: /v3/api-docs/professional-service
      - name: schedule-service
        url: /v3/api-docs/schedule-service
      - name: nutrition-service
        url: /v3/api-docs/nutrition-service
      - name: psychological-service
        url: /v3/api-docs/psychological-service
      - name: physical-activity-service
        url: /v3/api-docs/physical-activity-service
      - name: authentication-service
        url: /v3/api-docs/authentication-service
